### ISSUE TITLE
Illegible Discussion Slides

### ISSUE THREAD

**Issue by dk0r** [cball/ChainReactPhotobomb#34]
**Issue**: Discussion slides (on both [youtube ](https://youtu.be/W8X7t1qlT_w?t=238)and [speakerdeck](https://speakerdeck.com/cball/from-idea-to-app-store-a-guide-to-shipping-react-native-apps?slide=8)) with small font are illegible.

**Request**: Please post link to higher quality slides.

**Comment by cball** [comment]
Sorry about that! Here's a link to a higher quality pdf: https://drive.google.com/file/d/0B4qiJ3CfFSrqeXpjSVVBdUpyUEk/view?usp=sharing
